title: "Mi Portfolio"
description: "Un blog sobre programación"
url: "https://silviaar91.github.io"
baseurl: "/silviaar91.github.io"
theme: jekyll-theme-primer
plugins:
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-gist
  - jekyll-github-metadata
  - jekyll-relative-links
  - jekyll-readme-index
  - jekyll-default-layout
  - jekyll-titles-from-headings
paginate: 5
